### ISSUE TITLE
Placing obj files in ./o breaks the chtyp step, can't find the newly created executable

### ISSUE THREAD

**Issue by xandark** [jeremysrand/Apple2GSBuildPipeline#3]
This is the third issue I found...

Because I have 173 build side-effect files, I put all the .a .d .root .macros files in ./o by customizing this as:

`	OBJDIR=./o
`

But that breaks the final part of the build process. So I have to modify these:

line 129 of tail.mk

`	$(CHTYP) -t $(FILETYPE) $(AUXTYPE) $(TARGETDIR)/$(PGM)
`

change to:

`	$(CHTYP) -t $(FILETYPE) $(AUXTYPE) $(OBJDIR)/$(PGM)
`

otherwise I get this:

```
/home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/orca chtyp -t s16 -a 0x0000db03 ./"Animasia.3D"
./Animasia.3D: $0046: File not found
make[1]: *** [make/tail.mk:125: "Animasia.3D"] Error 1
make[1]: Leaving directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
make: *** [make/head.mk:94: all] Error 2
```

Looks like line 129 and 145 also have the same issue too.

I'm using this on KDE neon Linux.

**Comment by jeremysrand** [comment]
I appreciate the report but I am not sure there is an issue here.  The build defines three directories for build products:

GENDIR - This is a directory where code can be generated (if your build needs to generate code).
OBJDIR - This is the directory where object files will be created.
TARGETDIR - This is the directory where the executable(s) and disk image(s) will be created.

By default, outside of Xcode, these directories all default to "." which isn't all that good for most people.  And because I am trying to create the executable (and $PGM is the executable) in the TARGETDIR, I don't think I want to change this to OBJDIR instead.  It is intentional that the executable ends up in TARGETDIR.

My suggestion is that if you want to put your objects and executables in the same directory, then you should set both OBJDIR and TARGETDIR to the same directory.  Maybe that will solve the problem.

All that said, I am not sure why it wouldn't work if you have set OBJDIR to something specific but left TARGETDIR unset.  My guess is that things "work" from within Xcode because Xcode passes in absolute paths for these directories.  Setting OBJDIR to a relative path is maybe what the problem is.  I probably haven't tested with relative paths too much and maybe the relative paths should be turned into absolute paths using readlink or something similar within the makefiles themselves.

I am interested in knowing if setting TARGETDIR helps.  Also, if you can test with an absolute path (although I can understand you not wanting to use that long-term) in your OBJDIR, I would be interested in knowing if that works.  I think I can probably reproduce your problem here by overriding the directories from Xcode and use ./o as you are.  I will see if I can get some time to look at that tomorrow.  But if you have more feedback for me, that would be great.  Thanks!

**Comment by xandark** [comment]
> My suggestion is that if you want to put your objects and executables in the same directory, then you should set both OBJDIR and TARGETDIR to the same directory. Maybe that will solve the problem.

Sorry, I'm getting errors if I do that. I think I figured out the issue on my side.

With `TARGETDIR=.` manually set in my Makefile after the `include make/head.mk` directive, the linker is putting my executable in my ./o OBJDIR directory and therefore it is not being found by the remainder of the Make process and it fails.

This is the output of the make. Pay attention to the cd ./o ...

```
$ make
mkdir -p ./o . .
make[1]: Entering directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
[ "`uname`" = Darwin ] && defaults write "/home/michael/Library/Developer/Xcode/Plug-ins/OrcaM.ideplugin/Contents/Info.plist" DVTPlugInCompatibilityUUIDs -array `defaults read "/Applications/Xcode.app/Contents/Info.plist" DVTPlugInCompatibilityUUID` || true
make[1]: Leaving directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
make[1]: Entering directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
mkdir -p .
cd ./o; /home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/orca link -P   AniEvnt  AniObj4  AniTLin  AniAnim4  AppMovi2  AppErr  AppPipe  AniVert2  AppLList  AniHier2  AppPal2  AniMenu  AppVal  AniCur  AppRast  AppArray  AniObj2  AniObj  AniMenu2  AppStr  AppLayr  AppRast2  AniObj3  AniSys  AniSub2  AniColr  AppRect  AniDraw2  AppMenu  AniSlct  AniAnim  AniHier  AppUndo  AppList  AniRend  AppWin  AniTool4  AniMath  AniWrld  AppClip  AniProt  AniTool  AniSub3  AniAnim2  AniGno  AniObj5  AniList  AppData  AppMovi  AniDraw  AniSess  AniSub  AppGraph  AppCur  AppCtl  AniWin  AniSVert  AppMem  AniEdge  AniTLin2  AniTool2  AniAnim3  AppFile  AniTime  AniWrld2  AniVec  AniData  AniDlog  AppMem2  AppPoint  AppEvnt  AniTool3  AniObj6  AniMath3  AniWork2  AppTree  AniDXF  AniCam  AppVec  AppPal  AniWrld3  AniLayr  AppGno  AniVert  AppMovi3 keep=./"Animasia.3D"
/home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/orca chtyp -t s16 -a 0x0000db03 ./"Animasia.3D"
./Animasia.3D: $0046: File not found
make[1]: *** [make/tail.mk:125: "Animasia.3D"] Error 1
make[1]: Leaving directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
make: *** [make/head.mk:94: all] Error 2
```

The problem that I see is that the `cd ./o` right before the link step is making `TARGETDIR=.` now equivalent to ./o instead of simply .

Yes, with absolute paths, this issue goes away because it's all absolute. 

... and I just figured out the fix:

In tail.mk on line 128, change from

`	cd $(OBJDIR); $(LINK) $(LDFLAGS) $(patsubst $(OBJDIR)/%, %, $(BUILD_OBJS_NOSUFFIX)) keep=$(TARGETDIR)/$(PGM)
`

to:

`	$(LINK) $(LDFLAGS) $(patsubst $(OBJDIR)/%, $(OBJDIR)/%, $(BUILD_OBJS_NOSUFFIX)) keep=$(TARGETDIR)/$(PGM)
`

Then the make looks like this now:

```
mkdir -p ./o . .
make[1]: Entering directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
[ "`uname`" = Darwin ] && defaults write "/home/michael/Library/Developer/Xcode/Plug-ins/OrcaM.ideplugin/Contents/Info.plist" DVTPlugInCompatibilityUUIDs -array `defaults read "/Applications/Xcode.app/Contents/Info.plist" DVTPlugInCompatibilityUUID` || true
make[1]: Leaving directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
make[1]: Entering directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
mkdir -p .
/home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/orca link -P   ./o/AniEvnt  ./o/AniObj4  ./o/AniTLin  ./o/AniAnim4  ./o/AppMovi2  ./o/AppErr  ./o/AppPipe  ./o/AniVert2  ./o/AppLList  ./o/AniHier2  ./o/AppPal2  ./o/AniMenu  ./o/AppVal  ./o/AniCur  ./o/AppRast  ./o/AppArray  ./o/AniObj2  ./o/AniObj  ./o/AniMenu2  ./o/AppStr  ./o/AppLayr  ./o/AppRast2  ./o/AniObj3  ./o/AniSys  ./o/AniSub2  ./o/AniColr  ./o/AppRect  ./o/AniDraw2  ./o/AppMenu  ./o/AniSlct  ./o/AniAnim  ./o/AniHier  ./o/AppUndo  ./o/AppList  ./o/AniRend  ./o/AppWin  ./o/AniTool4  ./o/AniMath  ./o/AniWrld  ./o/AppClip  ./o/AniProt  ./o/AniTool  ./o/AniSub3  ./o/AniAnim2  ./o/AniGno  ./o/AniObj5  ./o/AniList  ./o/AppData  ./o/AppMovi  ./o/AniDraw  ./o/AniSess  ./o/AniSub  ./o/AppGraph  ./o/AppCur  ./o/AppCtl  ./o/AniWin  ./o/AniSVert  ./o/AppMem  ./o/AniEdge  ./o/AniTLin2  ./o/AniTool2  ./o/AniAnim3  ./o/AppFile  ./o/AniTime  ./o/AniWrld2  ./o/AniVec  ./o/AniData  ./o/AniDlog  ./o/AppMem2  ./o/AppPoint  ./o/AppEvnt  ./o/AniTool3  ./o/AniObj6  ./o/AniMath3  ./o/AniWork2  ./o/AppTree  ./o/AniDXF  ./o/AniCam  ./o/AppVec  ./o/AppPal  ./o/AniWrld3  ./o/AniLayr  ./o/AppGno  ./o/AniVert  ./o/AppMovi3 keep=./"Animasia.3D"
/home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/orca chtyp -t s16 -a 0x0000db03 ./"Animasia.3D"

```

**Comment by jeremysrand** [comment]
Agreed.  That is what is causing the problem.  Thanks for finding it.  Because TARGETDIR is an absolute path when building from Xcode, I don't see it.  Or if OBJDIR and TARGETDIR are both "." as they are by default, then it "work" by accident.

The reason I put the cd in there and did the link relative to the OBJDIR is because those absolute paths from Xcode are very long and the linker choked on the long arguments.  I figured one long name for the TARGETDIR was better than N long names with each object file.

I am still thinking about putting something at the top of tail.mk that turns any relative path in GENDIR, OBJDIR and TARGETDIR into absolute paths.  Then I think it will work for everyone.  But finding a portable way to do that isn't particularly easy.  I will see what I can do.

**Comment by jeremysrand** [comment]
I think I have just committed a fix for this which should work for you.  I was looking for a way to do this in the shell and then realized I could just use $(abspath ...) in tail.mk itself.  I tested this under MacOS with OBJDIR set to objs but TARGETDIR set to . and it worked fine for me.  I think this will work for everyone.

Now, the next problem you may have is the spaces in the path to the project which I can see in your examples above.  I haven't tested with that and it could be that I have problems with that.  I will test that now but I think we are closer.

**Comment by jeremysrand** [comment]
I just pushed another change.  Now, I only use $(abspath) in the actual link command itself.  That is safer and keeps the number of places where spaces can occur in a path because the project is in a path with a space to a minimum.  But while there, I did some testing with spaces in the path to the project and it is working for me with that also.  So, I am hoping you find this latest change to tail.mk good.

**Comment by xandark** [comment]
Okay this seems to work too. From the way that I had it before, my link step went from:

```
/home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/iix link -P   o/AniEvnt  o/AniObj4  o/AniTLin  o/AniAnim4  o/AppMovi2  o/AppErr  o/AppPipe  o/AniVert2  o/AppLList  o/AniHier2  o/AppPal2  o/AniMenu  o/AppVal  o/AniCur  o/AppRast  o/AppArray  o/AniObj2  o/AniObj  o/AniMenu2  o/AppStr  o/AppLayr  o/AppRast2  o/AniObj3  o/AniSys  o/AniSub2  o/AniColr  o/AppRect  o/AniDraw2  o/AppMenu  o/AniSlct  o/AniAnim  o/AniHier  o/AppUndo  o/AppList  o/AniRend  o/AppWin  o/AniTool4  o/AniMath  o/AniWrld  o/AppClip  o/AniProt  o/AniTool  o/AniSub3  o/AniAnim2  o/AniGno  o/AniObj5  o/AniList  o/AppData  o/AppMovi  o/AniDraw  o/AniSess  o/AniSub  o/AppGraph  o/AppCur  o/AppCtl  o/AniWin  o/AniSVert  o/AppMem  o/AniEdge  o/AniTLin2  o/AniTool2  o/AniAnim3  o/AppFile  o/AniTime  o/AniWrld2  o/AniVec  o/AniData  o/AniDlog  o/AppMem2  o/AppPoint  o/AppEvnt  o/AniTool3  o/AniObj6  o/AniMath3  o/AniWork2  o/AppTree  o/AniDXF  o/AniCam  o/AppVec  o/AppPal  o/AniWrld3  o/AniLayr  o/AppGno  o/AniVert  o/AppMovi3 keep=./"Animasia.3D"
/home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/iix chtyp -t s16 -a 0x0000db03 ./"Animasia.3D"
```

to using your $(abspath) :

```
cd o; /home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/iix link -P   AniEvnt  AniObj4  AniTLin  AniAnim4  AppMovi2  AppErr  AppPipe  AniVert2  AppLList  AniHier2  AppPal2  AniMenu  AppVal  AniCur  AppRast  AppArray  AniObj2  AniObj  AniMenu2  AppStr  AppLayr  AppRast2  AniObj3  AniSys  AniSub2  AniColr  AppRect  AniDraw2  AppMenu  AniSlct  AniAnim  AniHier  AppUndo  AppList  AniRend  AppWin  AniTool4  AniMath  AniWrld  AppClip  AniProt  AniTool  AniSub3  AniAnim2  AniGno  AniObj5  AniList  AppData  AppMovi  AniDraw  AniSess  AniSub  AppGraph  AppCur  AppCtl  AniWin  AniSVert  AppMem  AniEdge  AniTLin2  AniTool2  AniAnim3  AppFile  AniTime  AniWrld2  AniVec  AniData  AniDlog  AppMem2  AppPoint  AppEvnt  AniTool3  AniObj6  AniMath3  AniWork2  AppTree  AniDXF  AniCam  AppVec  AppPal  AniWrld3  AniLayr  AppGno  AniVert  AppMovi3 keep="/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D/"Animasia.3D""
/home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/iix chtyp -t s16 -a 0x0000db03 ./"Animasia.3D"
```

The tail end of the link argument string looks a little weird to me, it winds up not enquoting the actual target name, only the path...

`keep="/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D/"Animasia.3D""
`

...but it seems to output an executable with the right name in the right place.

So I'll concede that this works for me under Linux and let you close this if you're happy with it.

**Comment by jeremysrand** [comment]
Interesting.  I am not seeing that odd kind of quoting.  In the Makefile, do you have something that looks like this:

PGM="Animasia.3D"

If so, then I think you can fix this weird quoting by changing it to:

PGM=Animasia.3D

I think that may be why you are getting the double quoting happening.  The outer quotes are the ones I added and I suspect the inner quotes (which really just close and re-open the quotes if you ask the shell) are coming from the PGM variable.  The build shouldn't need those quotes to work.

If you do have quotes on that line and remove them and things don't work, let me know.  It would indicate another problem because they shouldn't be necessary.

**Comment by xandark** [comment]
Yes, you're right, I had quotes around my executable name. But strangely, when I remove the quotes, just as you indicated, it appears to skip over the link step entirely. And so I put the quotes back and it links just fine again. It's weird, and I cannot seem to figure out where in the tail.mk it is occluding because of the enquoted PGM file name.

So for contrast, this is what I get when I have PGM enquoted, as I always have:

```
$ make
mkdir -p o . .
make[1]: Entering directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
[ "`uname`" = Darwin ] && defaults write "/home/michael/Library/Developer/Xcode/Plug-ins/OrcaM.ideplugin/Contents/Info.plist" DVTPlugInCompatibilityUUIDs -array `defaults read "/Applications/Xcode.app/Contents/Info.plist" DVTPlugInCompatibilityUUID` || true
make[1]: Leaving directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
make[1]: Entering directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
mkdir -p .
cd o; /home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/iix link -P   AniEvnt  AniObj4  AniTLin  AniAnim4  AppMovi2  AppErr  AppPipe  AniVert2  AppLList  AniHier2  AppPal2  AniMenu  AppVal  AniCur  AppRast  AppArray  AniObj2  AniObj  AniMenu2  AppStr  AppLayr  AppRast2  AniObj3  AniSys  AniSub2  AniColr  AppRect  AniDraw2  AppMenu  AniSlct  AniAnim  AniHier  AppUndo  AppList  AniRend  AppWin  AniTool4  AniMath  AniWrld  AppClip  AniProt  AniTool  AniSub3  AniAnim2  AniGno  AniObj5  AniList  AppData  AppMovi  AniDraw  AniSess  AniSub  AppGraph  AppCur  AppCtl  AniWin  AniSVert  AppMem  AniEdge  AniTLin2  AniTool2  AniAnim3  AppFile  AniTime  AniWrld2  AniVec  AniData  AniDlog  AppMem2  AppPoint  AppEvnt  AniTool3  AniObj6  AniMath3  AniWork2  AppTree  AniDXF  AniCam  AppVec  AppPal  AniWrld3  AniLayr  AppGno  AniVert  AppMovi3 keep="/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D/"Animasia.3D""
/home/michael/Emulators/Apple.II/Development/GoldenGate/build/bin/iix chtyp -t s16 -a 0x0000db03 ./"Animasia.3D"
make/createDiskImage "./"Animasia.3D".2mg" "./"Animasia.3D"" "."
```

But when I change to `PGM=Animasia.3D` I get this where it skips the link step completely:

```
$ make
mkdir -p o . .
make[1]: Entering directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
[ "`uname`" = Darwin ] && defaults write "/home/michael/Library/Developer/Xcode/Plug-ins/OrcaM.ideplugin/Contents/Info.plist" DVTPlugInCompatibilityUUIDs -array `defaults read "/Applications/Xcode.app/Contents/Info.plist" DVTPlugInCompatibilityUUID` || true
make[1]: Leaving directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
make[1]: Entering directory '/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D'
make/createDiskImage "./Animasia.3D.2mg" "./Animasia.3D" "." 
```

What do you think?

**Comment by jeremysrand** [comment]
Not sure why that would be happening.  Did you try doing a "make clean" perhaps?  I wouldn't think that is required and I do have dependencies on the Makefile so changing the Makefile should trigger a complete rebuild I think but I am grasping at straws a little with this one.

In fact, if you do a "make" and then another "make", I think it should do nothing.  If repeated executions of make with the quotes around Animasia.3D results in the build always re-linking, that is actually not supposed to happen.  It should only re-link when something going into the link has changed.  Is it possible that it isn't linking because it doesn't think it needs to re-link because the binaries modification time is later than the object files?  If so, the question then becomes why did it think it needed to link when there were quotes?  And also why is it trying to create the disk image if the executable hasn't changed in the second example.  All of these things should be skipped if the dependencies say they haven't been changed.

**Comment by xandark** [comment]
You are right. I took out the quotes around my target name, did a make clean, and everything compiled and linked fine. I did another make and it smartly skipped over the link step. 

The last argument to the link step is for me now: `keep="/home/michael/Dev/Code C/Apple IIgs Projects/Animasia 3-D/Animasia.3D"` 

I'd say this can be marked as closed. Thank you for your attention :)
